---
version: "3.1"

services:
  openvas:
    build:
      context: .
    ports:
      - "127.0.0.1:4443:443"
    security_opt:
      - label=disable
    volumes:
      - ".gvm_pass:/run/secrets/gvm_pass:ro"
