---
version: "3.4"

services:
  openvas:
    build:
      context: .
    security_opt:
      - label=disable
    volumes:
      - "./feeds.tar.gz:/opt/gvm/initial_data/feeds.tar.gz:ro"
      - ".initial_feed_sync:/opt/gvm/initial_data/initial_feed_sync:ro"
